name: vos

description: TechAviate Flutter Project

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  shared_preferences: ^2.4.0
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  url_launcher: ^6.3.1
  loading_overlay_pro: ^2.1.1
  cached_network_image: ^3.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  talker_flutter: ^4.6.7
  flutter_svg: ^2.0.17
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.2.0
  table_calendar: ^3.1.3
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.14

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/foreground.png"
  remove_alpha_ios: true


### Uncomment this line to define a generate native splash screen

# flutter_native_splash:
#   color: "ffffff"
#   color_dark: "F6F8FB"
#   image: assets/images/splash.png
#   android: true
#   ios: true
#   ios_content_mode: scaleAspectFill
#   fullscreen: true # This makes the splash screen fullscreen on Android
#   android_gravity: fill # This ensures the image fills the screen

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/




  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
