// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:vos/models/habit_model.dart';
import 'package:vos/models/habit_record_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitModelAdapter());
    registerAdapter(HabitRecordModelAdapter());
  }
}
